### ISSUE TITLE
Can no longer resolve version 1.0.0

### ISSUE THREAD

**Issue by dnnyg33** [scalessec/Toast-Swift#10]
As the title says, version 1 isn't found.
Podfile contains
`pod 'Toast-Swift', '~> 1.0.0'`

output from running `pod install` is

> [!] Unable to satisfy the following requirements:

> `Toast-Swift (~> 1.0.0)` required by `Podfile`

**Comment by scalessec** [comment]
Do you need to use the older version? If you're on Xcode 7.3, I'd change your Podfile to `pod 'Toast-Swift', '~> 1.1.0'`. Otherwise if you have an explicit dependency on 1.0.0 try `pod 'Toast-Swift', '1.0.0'`. Also try `pod update Toast-Swift`. Please let me know what, if anything of this, worked for you.

**Comment by dnnyg33** [comment]
I'm using Xcode 7.2.1. So i'm not able to use 1.1.0 yet. I plan to upgrade soon, but can't yet. I tried using
`pod 'Toast-Swift', '1.0.0'` and got the same error as before. 
Running `pod update Toast-Swift` only produces

> [!] The 'Toast-Swift' Pod is not installed and cannot be updated

**Comment by scalessec** [comment]
Closing, since 1.0.0 is pretty outdated now anyway.
