### ISSUE TITLE
Enable toast top/bottom offset

### ISSUE THREAD

**Issue by everwanna** [scalessec/Toast-Swift#133]
Sometimes I need to set a bottom offset for the toast.

https://github.com/devxoul/Toaster has a pretty nice bottomOffsetPortrait/bottomOffsetLandscape settings.

It will be nice to have this feature.

**Comment by scalessec** [comment]
You can present the toast at any point, so I think the current functionality already satisfies this without needed to bloat the api.

**Comment by everwanna** [comment]
Yes, we can present at any point. As I know, when I need a bottom offset, I need to calculate the frame size of toast first, then I can calculate the correct point. But I do not see an easy way to do that. Any suggestions? Thanks!

**Comment by drinkius** [comment]
I agree with this point, it doesn't make sense to need to calculate the toast view frame when all we need is simply to move the toast up from the bottom edge of the screen.

Besides, it doesn't make sense to add `ToastManager.shared.style.verticalPadding` in the `centerPoint` calculation. Changing this style property both increases the size of the toast as well as moves it up relative to the bottom edge of the view. This should be a separate style property, not interconnected in such a weird way. I can make a PR if you agree with this change, otherwise I'd need to fork the library, but it's really a very logical thing to do

**Comment by everwanna** [comment]
@drinkius Thanks for your comment. FYI, there is a PR https://github.com/scalessec/Toast-Swift/pull/134

**Comment by Natai** [comment]
this is so necessary!
