### ISSUE TITLE
Toast over tableview

### ISSUE THREAD

**Issue by dotprox** [scalessec/Toast-Swift#20]
Is it normal? If yes, help please, how to make it fully over view?
iOS 9.3 swift (on device have the same problem (feature?))
<img width="325" alt="2016-04-24 19 37 12" src="https://cloud.githubusercontent.com/assets/6170103/14768810/1bffc6be-0a54-11e6-95f1-e9266ea46902.png">

**Comment by scalessec** [comment]
Present the toast in the table view's superview, instead of in the table view itself. If you're using a navigation controller this would be `self.navigationController.view.makeToast("qweqwe")` or alternatively you could use the window directly (although I wouldn't recommend this): `self.navigationController.view.makeToast("qweqwe")`

**Comment by dotprox** [comment]
Thanx 👍

**Comment by computerjulian** [comment]
This also solved my problem with the Toast view being scrolled, now it is fixed at bottom, thanx!

**Comment by serbuk** [comment]
Thanks! Would be good to mention it in the examples.

**Comment by cesarmtz93** [comment]
@scalessec in iOS 11 it's not being position at the end of the TVC

**Comment by scalessec** [comment]
It's working fine in iOS 11. Re-read this thread and make sure you're presenting the toast in the correct view. If you present the toast in a table view, it will position itself at the bottom of the table view and scroll with the table. If you want the toast on top of the table, you need to present the toast in one of the table view's superviews.
