### ISSUE TITLE
Not arm64 compliant

### ISSUE THREAD

**Issue by San-Jeevan** [scalessec/Toast-Swift#42]
"type metadata for (extension in myproject):__ObjC.UIView.(ToastError in _9435D8AD737309FD1AA87C6149FEA121)", referenced from:

ld: symbol(s) not found for architecture arm64

cant compile it on arm64 architecture.

**Comment by RegisStGelais** [comment]
I have the same issue when archiving

**Comment by btanner** [comment]
Same problem here.  No idea how to fix, but app deploys to connected devices or simulator, just can't archive.

**Comment by scalessec** [comment]
Xcode 8? Can you reproduce when you try to archive the Toast-Swift demo project? I just archived and exported an ad-hoc build of the demo project without issue.

**Comment by btanner** [comment]
I think I originally just copied Toast.Swift directly into my project in the Spring of 2016 and have been using it without issue since then.

The problem is now with XCode 8 using Swift 2.3.  It looks like you've updated to Swift 3 which I cannot move to quite yet because of other issues I'm fighting with.

I'll let you know after we get to Swift 3 if there are any probs. Please let me know if there is a Swift 2.3 file hanging around I can use :)

**Comment by RegisStGelais** [comment]
> The problem is now with XCode 8 using Swift 2.3. It looks like you've updated to Swift 3 which I cannot move to quite yet because of other issues I'm fighting with.

Same thing for me

**Comment by bijington** [comment]
@btanner @RegisStGelais this might be a little late however I encountered the same issue and found that set the Optimization Level to None for Release let me Archive. I also plan to move to Swift 3.0 at some point but it is quite daunting seeing all of those errors pop-up.

Here is the credit:
https://github.com/AliSoftware/SwiftGen/issues/57#issuecomment-159996671
