### ISSUE TITLE
Do not show toast on view item of tab view controller

### ISSUE THREAD

**Issue by gaalvarez** [scalessec/Toast-Swift#51]
A simple toast calle with:

`self.view.makeToast("msg")`

Do not show if the toast is called from view on tab view controller. If the view no is inside tab controller the toast is correct. 

I use toast.swift manually installed version 1.4.0 in xcode 7.2 with swift 2.2

**Comment by scalessec** [comment]
The toast is most likely behind the tab bar. 

You can display the toast on top of the tab bar by presenting it in the tab bar controller's view instead of `self.view`:

`self.tabBarController?.view.makeToast("msg")`

Or you could specify a position that works for you:

`self.view.makeToast("msg", duration: 2.0, position: CGPoint(x: 110.0, y: 110.0)`
