### ISSUE TITLE
Why use associated objects?

### ISSUE THREAD

**Issue by FruitAndAShape** [scalessec/Toast-Swift#53]
Why don't you put the `queue` on the `ToastManager`?

I reckon extensions don't allow stored properties for a reason, and using associated objects is going against the spirit of this.

**Comment by scalessec** [comment]
I strongly disagree. First, there's not just one queue per application there's a queue per each parent view (you can present a toast in any view, and each of those views has it's own queue). Second, you'd be introducing a spaghetti mess of global state by using a singleton to store strong references to toast views across multiple parent views and potentially even multiple view controllers. Not a good idea. With associated objects each view mains it's own state, and when that view is dealloc'd (for whatever reason) so is everything associated to it.

Lastly, extensions don't support stored properties for the same reason Objective-C categories don't allow stored properties -- so that extensions can be applied to code that has already been compiled  (as would be the case with an extension on `UIView`). Much of`UIKit` takes a similar approach.

**Comment by FruitAndAShape** [comment]
Good points. I'd wrap the queue and put it on the view controller then. It would be like a fancy label.
